In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
#print attributes of the array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
#print datatype of array
print("dtype:", x3.dtype)

In [4]:
#Array Indexing:Accessing single elements
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x1[0]

5

In [6]:
x1[3]

3

In [7]:
#to index from the end of the array, you can use negative indices:
x1[-1]

9

In [8]:
x1[-1]

9

In [9]:
#In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0, 0]

3

In [16]:
x2[2, -1]

7

In [13]:
#accessing entire row
x2[2,:]

array([1, 6, 7, 7])

In [14]:
#accessing entire column
x2[:,2]

array([2, 8, 7])

In [20]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [21]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [22]:
#extract 2x2 subarray
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [17]:
#Modifying Values
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [18]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])